//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESU_API
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DB_A3CA54_segu101274Entities : DbContext
    {
        public DB_A3CA54_segu101274Entities()
            : base("name=DB_A3CA54_segu101274Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<GCPS_SP_APIPlanificacionxEspecialista_Result> GCPS_SP_APIPlanificacionxEspecialista(Nullable<int> idEspecialista)
        {
            var idEspecialistaParameter = idEspecialista.HasValue ?
                new ObjectParameter("IdEspecialista", idEspecialista) :
                new ObjectParameter("IdEspecialista", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GCPS_SP_APIPlanificacionxEspecialista_Result>("GCPS_SP_APIPlanificacionxEspecialista", idEspecialistaParameter);
        }
    
        public virtual ObjectResult<GCPS_SP_APISucursalesxPlanificacion_Result> GCPS_SP_APISucursalesxPlanificacion(Nullable<int> idPlanificacion)
        {
            var idPlanificacionParameter = idPlanificacion.HasValue ?
                new ObjectParameter("IdPlanificacion", idPlanificacion) :
                new ObjectParameter("IdPlanificacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GCPS_SP_APISucursalesxPlanificacion_Result>("GCPS_SP_APISucursalesxPlanificacion", idPlanificacionParameter);
        }
    
        public virtual ObjectResult<GCPS_SP_APIAreasxSucursal_Result> GCPS_SP_APIAreasxSucursal(string cOD_SUCURSAL)
        {
            var cOD_SUCURSALParameter = cOD_SUCURSAL != null ?
                new ObjectParameter("COD_SUCURSAL", cOD_SUCURSAL) :
                new ObjectParameter("COD_SUCURSAL", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GCPS_SP_APIAreasxSucursal_Result>("GCPS_SP_APIAreasxSucursal", cOD_SUCURSALParameter);
        }
    
        public virtual ObjectResult<GCPS_SP_APIAreaSucursalDistancia_Result> GCPS_SP_APIAreaSucursalDistancia(Nullable<int> idPlanificacion, Nullable<int> idAreaSucursal)
        {
            var idPlanificacionParameter = idPlanificacion.HasValue ?
                new ObjectParameter("IdPlanificacion", idPlanificacion) :
                new ObjectParameter("IdPlanificacion", typeof(int));
    
            var idAreaSucursalParameter = idAreaSucursal.HasValue ?
                new ObjectParameter("IdAreaSucursal", idAreaSucursal) :
                new ObjectParameter("IdAreaSucursal", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GCPS_SP_APIAreaSucursalDistancia_Result>("GCPS_SP_APIAreaSucursalDistancia", idPlanificacionParameter, idAreaSucursalParameter);
        }
    
        public virtual ObjectResult<GCPS_SP_APIESPECIALISTALOGIN_Result> GCPS_SP_APIESPECIALISTALOGIN(string usuario, string pwd)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var pwdParameter = pwd != null ?
                new ObjectParameter("Pwd", pwd) :
                new ObjectParameter("Pwd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GCPS_SP_APIESPECIALISTALOGIN_Result>("GCPS_SP_APIESPECIALISTALOGIN", usuarioParameter, pwdParameter);
        }
    
        public virtual ObjectResult<GCPS_SP_APIProductoxCodigoBarra_Result> GCPS_SP_APIProductoxCodigoBarra(string cODIGOBARRAS)
        {
            var cODIGOBARRASParameter = cODIGOBARRAS != null ?
                new ObjectParameter("CODIGOBARRAS", cODIGOBARRAS) :
                new ObjectParameter("CODIGOBARRAS", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GCPS_SP_APIProductoxCodigoBarra_Result>("GCPS_SP_APIProductoxCodigoBarra", cODIGOBARRASParameter);
        }
    
        public virtual ObjectResult<GCPS_SP_APIProductoObservacionxProducto_Result> GCPS_SP_APIProductoObservacionxProducto(string cOD_PRODUCTO)
        {
            var cOD_PRODUCTOParameter = cOD_PRODUCTO != null ?
                new ObjectParameter("COD_PRODUCTO", cOD_PRODUCTO) :
                new ObjectParameter("COD_PRODUCTO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GCPS_SP_APIProductoObservacionxProducto_Result>("GCPS_SP_APIProductoObservacionxProducto", cOD_PRODUCTOParameter);
        }
    
        public virtual ObjectResult<GCPS_SP_APIPlanificacionDetalleIns_Result> GCPS_SP_APIPlanificacionDetalleIns(Nullable<int> idPlanificacion, string cOD_PRODUCTO, Nullable<int> idObservacion, string resultado)
        {
            var idPlanificacionParameter = idPlanificacion.HasValue ?
                new ObjectParameter("IdPlanificacion", idPlanificacion) :
                new ObjectParameter("IdPlanificacion", typeof(int));
    
            var cOD_PRODUCTOParameter = cOD_PRODUCTO != null ?
                new ObjectParameter("COD_PRODUCTO", cOD_PRODUCTO) :
                new ObjectParameter("COD_PRODUCTO", typeof(string));
    
            var idObservacionParameter = idObservacion.HasValue ?
                new ObjectParameter("IdObservacion", idObservacion) :
                new ObjectParameter("IdObservacion", typeof(int));
    
            var resultadoParameter = resultado != null ?
                new ObjectParameter("Resultado", resultado) :
                new ObjectParameter("Resultado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GCPS_SP_APIPlanificacionDetalleIns_Result>("GCPS_SP_APIPlanificacionDetalleIns", idPlanificacionParameter, cOD_PRODUCTOParameter, idObservacionParameter, resultadoParameter);
        }
    
        public virtual ObjectResult<GCPS_SP_APIPlanificacionDetallexIdPlanificacion_Result> GCPS_SP_APIPlanificacionDetallexIdPlanificacion(Nullable<int> idPlanificacion)
        {
            var idPlanificacionParameter = idPlanificacion.HasValue ?
                new ObjectParameter("IdPlanificacion", idPlanificacion) :
                new ObjectParameter("IdPlanificacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GCPS_SP_APIPlanificacionDetallexIdPlanificacion_Result>("GCPS_SP_APIPlanificacionDetallexIdPlanificacion", idPlanificacionParameter);
        }
    }
}
