//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESU.Datos.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class GCPS_PLANIFICACION
    {
        public int IdPlanificacion { get; set; }
        public int IdEspecialista { get; set; }
        public Nullable<int> IdLaboratorio { get; set; }
        public Nullable<int> IdPlanificacionOrigen { get; set; }
        public string NumeroPlanificacion { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFin { get; set; }
        public string TipoPlanificacion { get; set; }
        public string TipoUrgencia { get; set; }
        public string Observacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string Estado { get; set; }
        public Nullable<bool> EsJustificado { get; set; }
    }
}
