//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGESU.Datos.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TP3UPCEntities : DbContext
    {
        public TP3UPCEntities()
            : base("name=TP3UPCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GCPS_PLANIFICACION> GCPS_PLANIFICACION { get; set; }
    
        [DbFunction("TP3UPCEntities", "GCPS_FN_SplitString")]
        public virtual IQueryable<string> GCPS_FN_SplitString(string @string, string delimiter)
        {
            var stringParameter = @string != null ?
                new ObjectParameter("string", @string) :
                new ObjectParameter("string", typeof(string));
    
            var delimiterParameter = delimiter != null ?
                new ObjectParameter("delimiter", delimiter) :
                new ObjectParameter("delimiter", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<string>("[TP3UPCEntities].[GCPS_FN_SplitString](@string, @delimiter)", stringParameter, delimiterParameter);
        }
    
        public virtual ObjectResult<GCPS_SP_EspecialistaSelTodo_Result> GCPS_SP_EspecialistaSelTodo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GCPS_SP_EspecialistaSelTodo_Result>("GCPS_SP_EspecialistaSelTodo");
        }
    
        public virtual ObjectResult<GCPS_SP_LaboratorioSelTodo_Result> GCPS_SP_LaboratorioSelTodo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GCPS_SP_LaboratorioSelTodo_Result>("GCPS_SP_LaboratorioSelTodo");
        }
    
        public virtual ObjectResult<GCPS_SP_PlanificacionDetalleAct_Result> GCPS_SP_PlanificacionDetalleAct(Nullable<int> idPlanificacionDetalle, string resultado, Nullable<System.DateTime> fechaCheckin, Nullable<System.DateTime> fechaEdicion, Nullable<System.DateTime> fechaValidacion, Nullable<System.DateTime> fechaImpresion)
        {
            var idPlanificacionDetalleParameter = idPlanificacionDetalle.HasValue ?
                new ObjectParameter("IdPlanificacionDetalle", idPlanificacionDetalle) :
                new ObjectParameter("IdPlanificacionDetalle", typeof(int));
    
            var resultadoParameter = resultado != null ?
                new ObjectParameter("Resultado", resultado) :
                new ObjectParameter("Resultado", typeof(string));
    
            var fechaCheckinParameter = fechaCheckin.HasValue ?
                new ObjectParameter("FechaCheckin", fechaCheckin) :
                new ObjectParameter("FechaCheckin", typeof(System.DateTime));
    
            var fechaEdicionParameter = fechaEdicion.HasValue ?
                new ObjectParameter("FechaEdicion", fechaEdicion) :
                new ObjectParameter("FechaEdicion", typeof(System.DateTime));
    
            var fechaValidacionParameter = fechaValidacion.HasValue ?
                new ObjectParameter("FechaValidacion", fechaValidacion) :
                new ObjectParameter("FechaValidacion", typeof(System.DateTime));
    
            var fechaImpresionParameter = fechaImpresion.HasValue ?
                new ObjectParameter("FechaImpresion", fechaImpresion) :
                new ObjectParameter("FechaImpresion", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GCPS_SP_PlanificacionDetalleAct_Result>("GCPS_SP_PlanificacionDetalleAct", idPlanificacionDetalleParameter, resultadoParameter, fechaCheckinParameter, fechaEdicionParameter, fechaValidacionParameter, fechaImpresionParameter);
        }
    
        public virtual ObjectResult<GCPS_SP_PlanificacionDetalleSel_Result> GCPS_SP_PlanificacionDetalleSel(Nullable<int> idPlanificacion)
        {
            var idPlanificacionParameter = idPlanificacion.HasValue ?
                new ObjectParameter("IdPlanificacion", idPlanificacion) :
                new ObjectParameter("IdPlanificacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GCPS_SP_PlanificacionDetalleSel_Result>("GCPS_SP_PlanificacionDetalleSel", idPlanificacionParameter);
        }
    
        public virtual ObjectResult<GCPS_SP_ProductoSelAtributosxIdProducto_Result> GCPS_SP_ProductoSelAtributosxIdProducto(Nullable<int> idProducto)
        {
            var idProductoParameter = idProducto.HasValue ?
                new ObjectParameter("IdProducto", idProducto) :
                new ObjectParameter("IdProducto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GCPS_SP_ProductoSelAtributosxIdProducto_Result>("GCPS_SP_ProductoSelAtributosxIdProducto", idProductoParameter);
        }
    
        public virtual ObjectResult<GCPS_SP_ServidorSel_Result> GCPS_SP_ServidorSel()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GCPS_SP_ServidorSel_Result>("GCPS_SP_ServidorSel");
        }
    
        public virtual ObjectResult<GCPS_SP_ProductoSelTodo_Result> GCPS_SP_ProductoSelTodo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GCPS_SP_ProductoSelTodo_Result>("GCPS_SP_ProductoSelTodo");
        }
    
        public virtual ObjectResult<GCPS_SP_SucursalSelTodo_Result> GCPS_SP_SucursalSelTodo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GCPS_SP_SucursalSelTodo_Result>("GCPS_SP_SucursalSelTodo");
        }
    
        public virtual ObjectResult<GCPS_SP_ProductoEnPlanificacionSel_Result> GCPS_SP_ProductoEnPlanificacionSel()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GCPS_SP_ProductoEnPlanificacionSel_Result>("GCPS_SP_ProductoEnPlanificacionSel");
        }
    
        public virtual ObjectResult<GCPS_SP_PlanificacionIns_Result> GCPS_SP_PlanificacionIns(string xml)
        {
            var xmlParameter = xml != null ?
                new ObjectParameter("xml", xml) :
                new ObjectParameter("xml", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GCPS_SP_PlanificacionIns_Result>("GCPS_SP_PlanificacionIns", xmlParameter);
        }
    
        public virtual ObjectResult<GCPS_SP_PlanificacionSel_Result> GCPS_SP_PlanificacionSel(string fechaInicio, string fechaFin)
        {
            var fechaInicioParameter = fechaInicio != null ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(string));
    
            var fechaFinParameter = fechaFin != null ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GCPS_SP_PlanificacionSel_Result>("GCPS_SP_PlanificacionSel", fechaInicioParameter, fechaFinParameter);
        }
    
        public virtual ObjectResult<GCPS_SP_PlanificacionSelDetalle_Result> GCPS_SP_PlanificacionSelDetalle(Nullable<int> idPlanificacion)
        {
            var idPlanificacionParameter = idPlanificacion.HasValue ?
                new ObjectParameter("IdPlanificacion", idPlanificacion) :
                new ObjectParameter("IdPlanificacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GCPS_SP_PlanificacionSelDetalle_Result>("GCPS_SP_PlanificacionSelDetalle", idPlanificacionParameter);
        }
    
        public virtual ObjectResult<GCPS_SP_PlanificionSelxIdPlanificacion_Result> GCPS_SP_PlanificionSelxIdPlanificacion(Nullable<int> idPlanificacion)
        {
            var idPlanificacionParameter = idPlanificacion.HasValue ?
                new ObjectParameter("IdPlanificacion", idPlanificacion) :
                new ObjectParameter("IdPlanificacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GCPS_SP_PlanificionSelxIdPlanificacion_Result>("GCPS_SP_PlanificionSelxIdPlanificacion", idPlanificacionParameter);
        }
    
        public virtual ObjectResult<GCPS_SP_PlanificacionAct_Result> GCPS_SP_PlanificacionAct(Nullable<int> idPlanificacion, Nullable<int> idEspecialista, Nullable<int> idLaboratorio, Nullable<int> idPlanificacionOrigen, string numeroPlanificacion, Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin, string tipoPlanificacion, string tipoUrgencia, string observacion, string estado, string cOD_SUCURSAL)
        {
            var idPlanificacionParameter = idPlanificacion.HasValue ?
                new ObjectParameter("IdPlanificacion", idPlanificacion) :
                new ObjectParameter("IdPlanificacion", typeof(int));
    
            var idEspecialistaParameter = idEspecialista.HasValue ?
                new ObjectParameter("IdEspecialista", idEspecialista) :
                new ObjectParameter("IdEspecialista", typeof(int));
    
            var idLaboratorioParameter = idLaboratorio.HasValue ?
                new ObjectParameter("IdLaboratorio", idLaboratorio) :
                new ObjectParameter("IdLaboratorio", typeof(int));
    
            var idPlanificacionOrigenParameter = idPlanificacionOrigen.HasValue ?
                new ObjectParameter("IdPlanificacionOrigen", idPlanificacionOrigen) :
                new ObjectParameter("IdPlanificacionOrigen", typeof(int));
    
            var numeroPlanificacionParameter = numeroPlanificacion != null ?
                new ObjectParameter("NumeroPlanificacion", numeroPlanificacion) :
                new ObjectParameter("NumeroPlanificacion", typeof(string));
    
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(System.DateTime));
    
            var tipoPlanificacionParameter = tipoPlanificacion != null ?
                new ObjectParameter("TipoPlanificacion", tipoPlanificacion) :
                new ObjectParameter("TipoPlanificacion", typeof(string));
    
            var tipoUrgenciaParameter = tipoUrgencia != null ?
                new ObjectParameter("TipoUrgencia", tipoUrgencia) :
                new ObjectParameter("TipoUrgencia", typeof(string));
    
            var observacionParameter = observacion != null ?
                new ObjectParameter("Observacion", observacion) :
                new ObjectParameter("Observacion", typeof(string));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("Estado", estado) :
                new ObjectParameter("Estado", typeof(string));
    
            var cOD_SUCURSALParameter = cOD_SUCURSAL != null ?
                new ObjectParameter("COD_SUCURSAL", cOD_SUCURSAL) :
                new ObjectParameter("COD_SUCURSAL", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GCPS_SP_PlanificacionAct_Result>("GCPS_SP_PlanificacionAct", idPlanificacionParameter, idEspecialistaParameter, idLaboratorioParameter, idPlanificacionOrigenParameter, numeroPlanificacionParameter, fechaInicioParameter, fechaFinParameter, tipoPlanificacionParameter, tipoUrgenciaParameter, observacionParameter, estadoParameter, cOD_SUCURSALParameter);
        }
    
        public virtual ObjectResult<GCPS_SP_PlanificacionLaboratorioSel_Result> GCPS_SP_PlanificacionLaboratorioSel(Nullable<int> idPlanificacion)
        {
            var idPlanificacionParameter = idPlanificacion.HasValue ?
                new ObjectParameter("IdPlanificacion", idPlanificacion) :
                new ObjectParameter("IdPlanificacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GCPS_SP_PlanificacionLaboratorioSel_Result>("GCPS_SP_PlanificacionLaboratorioSel", idPlanificacionParameter);
        }
    
        public virtual ObjectResult<GCPS_SP_PlanificacionDetalleSelxIdPlanificacionDetalle_Result> GCPS_SP_PlanificacionDetalleSelxIdPlanificacionDetalle(Nullable<int> idPlanificacionDetalle)
        {
            var idPlanificacionDetalleParameter = idPlanificacionDetalle.HasValue ?
                new ObjectParameter("IdPlanificacionDetalle", idPlanificacionDetalle) :
                new ObjectParameter("IdPlanificacionDetalle", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GCPS_SP_PlanificacionDetalleSelxIdPlanificacionDetalle_Result>("GCPS_SP_PlanificacionDetalleSelxIdPlanificacionDetalle", idPlanificacionDetalleParameter);
        }
    
        public virtual ObjectResult<GCPS_SP_PlanificacionDetalleActxCheckin_Result> GCPS_SP_PlanificacionDetalleActxCheckin(Nullable<int> idPlanificacion, string cOD_PRODUCTO, Nullable<System.DateTime> fechaCheckin)
        {
            var idPlanificacionParameter = idPlanificacion.HasValue ?
                new ObjectParameter("IdPlanificacion", idPlanificacion) :
                new ObjectParameter("IdPlanificacion", typeof(int));
    
            var cOD_PRODUCTOParameter = cOD_PRODUCTO != null ?
                new ObjectParameter("COD_PRODUCTO", cOD_PRODUCTO) :
                new ObjectParameter("COD_PRODUCTO", typeof(string));
    
            var fechaCheckinParameter = fechaCheckin.HasValue ?
                new ObjectParameter("FechaCheckin", fechaCheckin) :
                new ObjectParameter("FechaCheckin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GCPS_SP_PlanificacionDetalleActxCheckin_Result>("GCPS_SP_PlanificacionDetalleActxCheckin", idPlanificacionParameter, cOD_PRODUCTOParameter, fechaCheckinParameter);
        }
    
        public virtual ObjectResult<GCPS_SP_EquipmentSel_Result> GCPS_SP_EquipmentSel()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GCPS_SP_EquipmentSel_Result>("GCPS_SP_EquipmentSel");
        }
    
        public virtual ObjectResult<GCPS_SP_QC_LEVEY_JENNINGS_Result> GCPS_SP_QC_LEVEY_JENNINGS(Nullable<int> idPrueba, Nullable<int> idEquipment)
        {
            var idPruebaParameter = idPrueba.HasValue ?
                new ObjectParameter("IdPrueba", idPrueba) :
                new ObjectParameter("IdPrueba", typeof(int));
    
            var idEquipmentParameter = idEquipment.HasValue ?
                new ObjectParameter("IdEquipment", idEquipment) :
                new ObjectParameter("IdEquipment", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GCPS_SP_QC_LEVEY_JENNINGS_Result>("GCPS_SP_QC_LEVEY_JENNINGS", idPruebaParameter, idEquipmentParameter);
        }
    
        public virtual ObjectResult<GCPS_SP_QCEquipmentPruebaSelxIdEquipment_Result> GCPS_SP_QCEquipmentPruebaSelxIdEquipment(Nullable<int> idEquipment)
        {
            var idEquipmentParameter = idEquipment.HasValue ?
                new ObjectParameter("IdEquipment", idEquipment) :
                new ObjectParameter("IdEquipment", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GCPS_SP_QCEquipmentPruebaSelxIdEquipment_Result>("GCPS_SP_QCEquipmentPruebaSelxIdEquipment", idEquipmentParameter);
        }
    
        public virtual ObjectResult<GCPS_SP_ReporteCampo_Result> GCPS_SP_ReporteCampo(string cOD_PRODUCTO, string fECHAINICIO, string fECHAFIN)
        {
            var cOD_PRODUCTOParameter = cOD_PRODUCTO != null ?
                new ObjectParameter("COD_PRODUCTO", cOD_PRODUCTO) :
                new ObjectParameter("COD_PRODUCTO", typeof(string));
    
            var fECHAINICIOParameter = fECHAINICIO != null ?
                new ObjectParameter("FECHAINICIO", fECHAINICIO) :
                new ObjectParameter("FECHAINICIO", typeof(string));
    
            var fECHAFINParameter = fECHAFIN != null ?
                new ObjectParameter("FECHAFIN", fECHAFIN) :
                new ObjectParameter("FECHAFIN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GCPS_SP_ReporteCampo_Result>("GCPS_SP_ReporteCampo", cOD_PRODUCTOParameter, fECHAINICIOParameter, fECHAFINParameter);
        }
    
        public virtual ObjectResult<GCPS_SP_ObservacionesSugerenciasSel_Result> GCPS_SP_ObservacionesSugerenciasSel()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GCPS_SP_ObservacionesSugerenciasSel_Result>("GCPS_SP_ObservacionesSugerenciasSel");
        }
    }
}
